import type { RestaurantConfig, MenuItem, Coupon, Review } from "./types";

export const RESTAURANT: RestaurantConfig = {
  name: "Abhiruchi",
  tagline: "Authentic South Indian Cuisine in the Heart of Sheffield",
  est: 2000,
  address: "142 Ecclesall Road, Sheffield, S11 8JD",
  phone: "+44 114 267 8899",
  email: "hello@abhiruchi.co.uk",
  hours: [
    { day: "Mon – Thu", time: "12:00pm – 10:00pm" },
    { day: "Fri – Sat", time: "12:00pm – 11:00pm" },
    { day: "Sunday",    time: "12:00pm – 9:30pm" },
  ],
  minOrder: 15,
  deliveryCharge: 2.99,
  freeDeliveryThreshold: 35,
};

export const CATEGORIES = [
  "All",
  "Tiffins",
  "Snacks",
  "Starters",
  "Biryanis",
  "Curries",
  "Rice",
  "Fried Rice & Noodles",
  "Pizza",
  "Burgers & Wraps",
  "Fish & Chips",
  "Beverages",
  "Desserts",
];

export const MENU: MenuItem[] = [
  // ── TIFFINS ──────────────────────────────────────────────────────────────
  { id: "plain-dosa",            name: "Plain Dosa",                  price: 3.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "A crispy, golden South Indian crepe made from fermented rice and lentil batter." },
  { id: "onion-dosa",            name: "Onion Dosa",                  price: 4.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Crispy dosa topped with finely chopped onions for extra flavour and crunch." },
  { id: "masala-dosa",           name: "Masala Dosa",                 price: 5.49,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Classic dosa filled with spiced mashed potato masala, served with chutney and sambar.", popular: true },
  { id: "mysore-masala-dosa",    name: "Mysore Masala Dosa",          price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "A spicy twist with Mysore chutney and stuffed with flavourful potato masala." },
  { id: "ghee-podi-dosa",        name: "Ghee Podi Dosa",              price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Dosa spread with aromatic ghee and sprinkled with spiced lentil podi." },
  { id: "ghee-karam-dosa",       name: "Ghee Karam Dosa",             price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Crispy dosa coated with ghee and fiery karam spice mix." },
  { id: "egg-dosa",              name: "Egg Dosa",                    price: 5.99,  category: "Tiffins",             veg: false, emoji: "🍳", desc: "Dosa topped with a seasoned egg layer, freshly cooked on the griddle." },
  { id: "chicken-masala-dosa",   name: "Chicken Masala Dosa",         price: 6.99,  category: "Tiffins",             veg: false, emoji: "🫓", desc: "A hearty dosa filled with rich and flavourful chicken masala." },
  { id: "plain-idly",            name: "Plain Idly (4 pcs)",          price: 4.99,  category: "Tiffins",             veg: true,  emoji: "🍚", desc: "Soft, fluffy steamed rice cakes served with chutney." },
  { id: "sambar-idly",           name: "Sambar Idly (4 pcs)",         price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🍚", desc: "Idlies soaked in hot, flavourful lentil sambar." },
  { id: "ghee-podi-idly",        name: "Ghee Podi Idly (9 pcs)",      price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🍚", desc: "Mini idlies tossed in ghee and coated with aromatic spiced podi." },
  { id: "mysore-bonda",          name: "Mysore Bonda (5 pcs)",        price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🍡", desc: "Crispy outside and soft inside, deep-fried savoury dumplings." },
  { id: "poori-curry",           name: "Poori with Curry (2 pcs)",    price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Fluffy fried bread served with a deliciously spiced curry." },
  { id: "chapathi-curry",        name: "Chapathi with Curry (2 pcs)", price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Soft whole wheat flatbreads served with flavourful curry." },
  { id: "paratha-sherwa",        name: "Paratha with Sherwa (2 pcs)", price: 5.99,  category: "Tiffins",             veg: true,  emoji: "🫓", desc: "Layered, flaky flatbreads served with rich, aromatic gravy." },
  { id: "khichdi-sherwa",        name: "Khichdi with Sherwa",         price: 6.99,  category: "Tiffins",             veg: true,  emoji: "🍲", desc: "Comforting rice and lentil dish served with spiced gravy." },

  // ── SNACKS ────────────────────────────────────────────────────────────────
  { id: "punugulu",              name: "Punugulu (~16 pcs)",          price: 4.99,  category: "Snacks",              veg: true,  emoji: "🍡", desc: "Crispy deep-fried dumplings made from fermented dosa batter, soft inside and crunchy outside." },
  { id: "ghee-karam-punugulu",   name: "Ghee Karam Punugulu",        price: 5.99,  category: "Snacks",              veg: true,  emoji: "🍡", desc: "Punugulu tossed in aromatic ghee and spicy karam powder for extra flavour." },
  { id: "mirchi-bajji",          name: "Mirchi Bajji",                price: 3.00,  category: "Snacks",              veg: true,  emoji: "🌶️", desc: "Large green chillies dipped in gram flour batter and deep-fried to perfection." },
  { id: "cut-bajji",             name: "Cut Bajji",                   price: 3.49,  category: "Snacks",              veg: true,  emoji: "🌶️", desc: "Sliced mirchi bajji topped with onions, chutneys, and spices for a street-style taste." },
  { id: "onion-pakoda",          name: "Onion Pakoda",                price: 2.99,  category: "Snacks",              veg: true,  emoji: "🧅", desc: "Crispy fritters made with sliced onions, gram flour, and spices." },
  { id: "pani-puri",             name: "Pani Puri (8 pcs)",          price: 3.00,  category: "Snacks",              veg: true,  emoji: "🫧", desc: "Crispy hollow puris filled with spicy tangy water, potatoes, and chickpeas." },
  { id: "veg-spring-rolls",      name: "Veg Spring Rolls (2 pcs)",   price: 2.49,  category: "Snacks",              veg: true,  emoji: "🥢", desc: "Crispy rolls stuffed with seasoned vegetables." },
  { id: "veg-samosa",            name: "Veg Samosa (4 pcs)",         price: 3.29,  category: "Snacks",              veg: true,  emoji: "🥟", desc: "Golden fried pastry filled with spiced potatoes and peas." },
  { id: "chicken-samosa",        name: "Chicken Samosa (4 pcs)",     price: 3.49,  category: "Snacks",              veg: false, emoji: "🥟", desc: "Crispy pastry stuffed with flavourful minced chicken filling." },
  { id: "snack-mix",             name: "Mix (Spring Roll + Samosas)", price: 3.49,  category: "Snacks",              veg: false, emoji: "🍱", desc: "A combo of 1 veg spring roll, 1 veg samosa, and 1 chicken samosa." },
  { id: "snack-onion-rings",     name: "Onion Rings (6 pcs)",        price: 3.99,  category: "Snacks",              veg: true,  emoji: "🧅", desc: "Crispy battered onion rings, deep-fried until golden." },
  { id: "snack-mozz-sticks",     name: "Mozzarella Sticks (6 pcs)",  price: 4.99,  category: "Snacks",              veg: true,  emoji: "🧀", desc: "Breaded sticks filled with melted mozzarella cheese." },
  { id: "indian-omelette",       name: "Indian Style Omelette",      price: 1.99,  category: "Snacks",              veg: false, emoji: "🍳", desc: "Fluffy omelette cooked with onions, green chillies, and spices." },

  // ── STARTERS – VEG ───────────────────────────────────────────────────────
  { id: "veg-manchurian",        name: "Veg Manchurian",              price: 5.99,  category: "Starters",            veg: true,  emoji: "🥦", desc: "Crispy vegetable balls tossed in a tangy Indo-Chinese sauce." },
  { id: "gobi-manchurian",       name: "Gobi Manchurian",             price: 5.99,  category: "Starters",            veg: true,  emoji: "🥦", desc: "Fried cauliflower florets coated in spicy Manchurian sauce." },
  { id: "chilli-paneer",         name: "Chilli Paneer",               price: 7.99,  category: "Starters",            veg: true,  emoji: "🧀", desc: "Paneer cubes stir-fried with peppers and onions in a spicy chilli sauce.", popular: true },
  { id: "chilli-gobi",           name: "Chilli Gobi",                 price: 6.99,  category: "Starters",            veg: true,  emoji: "🥦", desc: "Crispy cauliflower tossed in a hot and tangy chilli sauce." },
  { id: "paneer-65",             name: "Paneer 65",                   price: 6.99,  category: "Starters",            veg: true,  emoji: "🧀", desc: "Deep-fried paneer pieces coated in a spicy South Indian marinade." },
  { id: "gobi-65",               name: "Gobi 65",                     price: 5.99,  category: "Starters",            veg: true,  emoji: "🥦", desc: "Crispy cauliflower bites with bold spices and herbs." },
  { id: "garlic-mushroom",       name: "Garlic Mushroom",             price: 6.49,  category: "Starters",            veg: true,  emoji: "🍄", desc: "Mushrooms sautéed in garlic, herbs, and light spices." },

  // ── STARTERS – NON-VEG ───────────────────────────────────────────────────
  { id: "chicken-wings",         name: "Chicken Wings (6 pcs)",       price: 5.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Juicy wings in Tandoori, Spicy, BBQ, or Buffalo flavours.", popular: true },
  { id: "chicken-strips",        name: "Chicken Strips (6 pcs)",      price: 5.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Crispy chicken strips, perfectly seasoned and fried." },
  { id: "chicken-bites",         name: "Chicken Bites (6 pcs)",       price: 5.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Bite-sized crispy chicken pieces, great for sharing." },
  { id: "nuggets",               name: "Nuggets (6 pcs)",             price: 4.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Classic golden chicken nuggets with a crunchy coating." },
  { id: "chicken-manchurian",    name: "Chicken Manchurian",          price: 6.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Crispy chicken tossed in a spicy Indo-Chinese sauce." },
  { id: "chilli-chicken",        name: "Chilli Chicken",              price: 6.99,  category: "Starters",            veg: false, emoji: "🌶️", desc: "Fried chicken pieces cooked with peppers in a spicy chilli sauce." },
  { id: "chilli-prawn",          name: "Chilli Prawn",                price: 7.99,  category: "Starters",            veg: false, emoji: "🦐", desc: "Juicy prawns stir-fried in a bold and spicy chilli sauce." },
  { id: "chicken-65",            name: "Chicken 65",                  price: 6.49,  category: "Starters",            veg: false, emoji: "🌶️", desc: "Popular South Indian spicy fried chicken with curry leaves.", popular: true },
  { id: "prawn-65",              name: "Prawn 65",                    price: 7.49,  category: "Starters",            veg: false, emoji: "🦐", desc: "Crispy prawns coated in aromatic spices." },
  { id: "chicken-pakoda",        name: "Chicken Pakoda",              price: 5.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Deep-fried chicken fritters with flour and spices." },
  { id: "dragon-chicken",        name: "Dragon Chicken",              price: 6.49,  category: "Starters",            veg: false, emoji: "🐉", desc: "Crispy chicken tossed in a sweet, spicy, and tangy sauce." },
  { id: "pepper-chicken",        name: "Pepper Chicken",              price: 6.49,  category: "Starters",            veg: false, emoji: "🍗", desc: "Chicken cooked with freshly ground black pepper for a bold flavour." },
  { id: "chicken-lollipop",      name: "Chicken Lollipop (4 pcs)",   price: 6.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Frenched chicken wings fried and coated in spicy sauce." },
  { id: "chicken-ghee-roast",    name: "Chicken Ghee Roast",          price: 6.99,  category: "Starters",            veg: false, emoji: "🍗", desc: "Rich and spicy chicken cooked in ghee with roasted spices." },
  { id: "lamb-pepper-fry",       name: "Lamb Pepper Fry",             price: 7.49,  category: "Starters",            veg: false, emoji: "🥩", desc: "Tender lamb cooked with black pepper and spices." },
  { id: "lamb-ghee-roast",       name: "Lamb Ghee Roast",             price: 7.49,  category: "Starters",            veg: false, emoji: "🥩", desc: "Slow-cooked lamb in ghee with aromatic spices." },
  { id: "prawn-pepper-fry",      name: "Prawn Pepper Fry",            price: 7.49,  category: "Starters",            veg: false, emoji: "🦐", desc: "Prawns sautéed with black pepper and spices." },
  { id: "prawn-ghee-roast",      name: "Prawn Ghee Roast",            price: 7.49,  category: "Starters",            veg: false, emoji: "🦐", desc: "Juicy prawns cooked in rich ghee and roasted spices." },

  // ── BIRYANIS ──────────────────────────────────────────────────────────────
  { id: "chicken-dum-biryani",      name: "Chicken Dum Biryani",          price: 11.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Aromatic basmati rice slow-cooked with bone-in chicken, herbs, and traditional spices.", popular: true, hero: true },
  { id: "chicken-boneless-biryani", name: "Chicken Boneless Biryani",     price: 11.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Fragrant rice cooked with tender boneless chicken pieces and rich spices." },
  { id: "chicken-lollipop-biryani", name: "Chicken Lollipop Biryani",     price: 13.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Spiced rice served with crispy, flavourful chicken lollipops." },
  { id: "chicken-65-biryani",       name: "Chicken 65 Biryani",           price: 13.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Biryani topped with spicy, deep-fried Chicken 65 pieces." },
  { id: "fry-piece-biryani",        name: "Fry Piece Biryani",            price: 14.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Rice served with crispy fried chicken pieces infused with spices." },
  { id: "gongura-chicken-biryani",  name: "Gongura Chicken Biryani",      price: 14.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Tangy gongura leaves blended with spiced chicken and aromatic rice." },
  { id: "chicken-mughalai-biryani", name: "Chicken Mughalai Biryani",     price: 15.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Rich and creamy Mughal-style biryani with mild spices and tender chicken." },
  { id: "lamb-biryani",             name: "Lamb Biryani",                 price: 15.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Slow-cooked basmati rice with tender lamb and traditional spices." },
  { id: "gongura-lamb-biryani",     name: "Gongura Lamb Biryani",         price: 16.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "A tangy twist with gongura leaves and succulent lamb pieces." },
  { id: "prawn-biryani",            name: "Prawn Biryani",                price: 14.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Flavourful rice cooked with juicy prawns and aromatic spices." },
  { id: "prawn-65-biryani",         name: "Prawn 65 Biryani",             price: 15.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Flavourful rice topped with spicy, deep-fried prawn pieces." },
  { id: "egg-biryani",              name: "Egg Biryani",                  price: 11.99, category: "Biryanis", veg: false, emoji: "🍛", desc: "Spiced rice layered with boiled eggs and aromatic masala." },
  { id: "veg-biryani",              name: "Veg Biryani",                  price: 11.99, category: "Biryanis", veg: true,  emoji: "🍛", desc: "A mix of fresh vegetables cooked with fragrant basmati rice and spices." },
  { id: "mushroom-biryani",         name: "Mushroom Biryani",             price: 12.99, category: "Biryanis", veg: true,  emoji: "🍛", desc: "Aromatic rice cooked with mushrooms and mild spices." },
  { id: "paneer-biryani",           name: "Paneer Biryani",               price: 13.99, category: "Biryanis", veg: true,  emoji: "🍛", desc: "Soft paneer cubes cooked with flavoured rice and spices." },
  { id: "kaju-paneer-biryani",      name: "Kaju Paneer Biryani",          price: 14.99, category: "Biryanis", veg: true,  emoji: "🍛", desc: "Rich biryani with paneer and cashews for a creamy, nutty taste." },

  // ── CURRIES – VEG ────────────────────────────────────────────────────────
  { id: "dal-tadka",             name: "Dal Tadka",                   price: 6.99,  category: "Curries",             veg: true,  emoji: "🫘", desc: "Yellow lentils tempered with garlic, cumin, and spices." },
  { id: "spinach-dal",           name: "Spinach Dal (Palak Dal)",     price: 7.49,  category: "Curries",             veg: true,  emoji: "🥬", desc: "Lentils cooked with fresh spinach and mild spices." },
  { id: "veg-kurma",             name: "Vegetable Kurma",             price: 6.99,  category: "Curries",             veg: true,  emoji: "🥦", desc: "Mixed vegetables in a creamy coconut-based curry." },
  { id: "paneer-masala",         name: "Paneer Masala",               price: 7.49,  category: "Curries",             veg: true,  emoji: "🧀", desc: "Paneer cubes cooked in a rich tomato-based gravy." },
  { id: "paneer-butter-masala",  name: "Paneer Butter Masala",        price: 7.99,  category: "Curries",             veg: true,  emoji: "🧀", desc: "Creamy and mildly sweet curry with butter and paneer.", popular: true },
  { id: "paneer-tikka-masala",   name: "Paneer Tikka Masala",         price: 7.99,  category: "Curries",             veg: true,  emoji: "🧀", desc: "Grilled paneer cooked in a spiced, smoky masala sauce." },

  // ── CURRIES – NON-VEG ────────────────────────────────────────────────────
  { id: "egg-masala-curry",      name: "Egg Masala Curry",            price: 6.99,  category: "Curries",             veg: false, emoji: "🥚", desc: "Boiled eggs cooked in a rich and spicy gravy." },
  { id: "chicken-masala-curry",  name: "Chicken Masala Curry",        price: 7.49,  category: "Curries",             veg: false, emoji: "🍲", desc: "Classic chicken curry with aromatic spices." },
  { id: "butter-chicken",        name: "Butter Chicken Masala",       price: 7.99,  category: "Curries",             veg: false, emoji: "🍲", desc: "Creamy tomato-based curry with tender chicken.", popular: true },
  { id: "chicken-tikka-masala",  name: "Chicken Tikka Masala",        price: 7.99,  category: "Curries",             veg: false, emoji: "🍲", desc: "Grilled chicken pieces in a rich, spiced sauce." },
  { id: "chicken-milagu-curry",  name: "Chicken Milagu Curry",        price: 7.49,  category: "Curries",             veg: false, emoji: "🌶️", desc: "South Indian style pepper chicken curry with bold flavours." },
  { id: "gongura-chicken-curry", name: "Gongura Chicken Curry",       price: 7.49,  category: "Curries",             veg: false, emoji: "🍲", desc: "Tangy gongura leaves cooked with chicken and spices." },
  { id: "chicken-kurma",         name: "Chicken Kurma",               price: 7.99,  category: "Curries",             veg: false, emoji: "🍲", desc: "Mild, creamy chicken curry with coconut and spices." },
  { id: "gongura-lamb-curry",    name: "Gongura Lamb Curry",          price: 8.49,  category: "Curries",             veg: false, emoji: "🥩", desc: "Lamb cooked with tangy gongura leaves and spices." },
  { id: "lamb-masala-curry",     name: "Lamb Masala Curry",           price: 8.49,  category: "Curries",             veg: false, emoji: "🥩", desc: "Rich and flavourful lamb curry with traditional spices." },
  { id: "lamb-kurma",            name: "Lamb Kurma",                  price: 8.49,  category: "Curries",             veg: false, emoji: "🥩", desc: "Creamy coconut-based lamb curry." },
  { id: "lamb-milagu-curry",     name: "Lamb Milagu Curry",           price: 8.49,  category: "Curries",             veg: false, emoji: "🥩", desc: "Spicy black pepper lamb curry." },
  { id: "prawn-masala-curry",    name: "Prawn Masala Curry",          price: 8.99,  category: "Curries",             veg: false, emoji: "🦐", desc: "Prawns cooked in a rich and spicy masala gravy." },

  // ── RICE ──────────────────────────────────────────────────────────────────
  { id: "plain-rice",            name: "Plain Rice",                  price: 2.99,  category: "Rice",                veg: true,  emoji: "🍚", desc: "Steamed basmati rice." },
  { id: "pulao-rice",            name: "Pulao Rice",                  price: 3.49,  category: "Rice",                veg: true,  emoji: "🍚", desc: "Lightly spiced rice with vegetables." },
  { id: "ghee-rice",             name: "Ghee Rice",                   price: 3.99,  category: "Rice",                veg: true,  emoji: "🍚", desc: "Aromatic rice cooked with clarified butter." },
  { id: "jeera-rice",            name: "Jeera Rice",                  price: 3.99,  category: "Rice",                veg: true,  emoji: "🍚", desc: "Fragrant rice tempered with cumin seeds." },
  { id: "mushroom-rice",         name: "Mushroom Rice",               price: 4.49,  category: "Rice",                veg: true,  emoji: "🍚", desc: "Rice cooked with mushrooms and spices." },
  { id: "plain-egg-rice",        name: "Plain Egg Rice",              price: 4.49,  category: "Rice",                veg: false, emoji: "🍚", desc: "Fried rice with egg and mild seasoning." },

  // ── FRIED RICE & NOODLES ─────────────────────────────────────────────────
  { id: "veg-fried-rice",              name: "Veg Fried Rice",              price: 6.99,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍳", desc: "Classic stir-fried rice with vegetables." },
  { id: "veg-manchurian-fried-rice",   name: "Veg Manchurian Fried Rice",   price: 7.49,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍳", desc: "Rice tossed with Manchurian-style vegetables." },
  { id: "gobi-manchurian-fried-rice",  name: "Gobi Manchurian Fried Rice",  price: 7.49,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍳", desc: "Fried rice with crispy cauliflower Manchurian." },
  { id: "mushroom-fried-rice",         name: "Mushroom Fried Rice",         price: 7.49,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍳", desc: "Rice stir-fried with mushrooms." },
  { id: "paneer-fried-rice",           name: "Paneer Fried Rice",           price: 7.99,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍳", desc: "Rice with paneer cubes and spices." },
  { id: "egg-fried-rice",              name: "Egg Fried Rice",              price: 7.99,  category: "Fried Rice & Noodles", veg: false, emoji: "🍳", desc: "Rice stir-fried with eggs and seasoning." },
  { id: "chicken-fried-rice",          name: "Chicken Fried Rice",          price: 7.99,  category: "Fried Rice & Noodles", veg: false, emoji: "🍳", desc: "Classic chicken stir-fried rice." },
  { id: "chicken-manchurian-fr",       name: "Chicken Manchurian Fried Rice", price: 8.49, category: "Fried Rice & Noodles", veg: false, emoji: "🍳", desc: "Rice mixed with spicy chicken Manchurian." },
  { id: "prawn-fried-rice",            name: "Prawn Fried Rice",            price: 8.49,  category: "Fried Rice & Noodles", veg: false, emoji: "🍳", desc: "Rice stir-fried with prawns and spices." },
  { id: "veg-noodles",                 name: "Veg Noodles",                 price: 6.99,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍜", desc: "Stir-fried noodles with vegetables." },
  { id: "veg-manchurian-noodles",      name: "Veg Manchurian Noodles",      price: 7.49,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍜", desc: "Noodles tossed with Manchurian-style vegetables." },
  { id: "gobi-manchurian-noodles",     name: "Gobi Manchurian Noodles",     price: 7.49,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍜", desc: "Noodles with crispy cauliflower Manchurian." },
  { id: "mushroom-noodles",            name: "Mushroom Noodles",            price: 7.49,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍜", desc: "Noodles stir-fried with mushrooms." },
  { id: "paneer-noodles",              name: "Paneer Noodles",              price: 7.99,  category: "Fried Rice & Noodles", veg: true,  emoji: "🍜", desc: "Noodles with paneer and spices." },
  { id: "egg-noodles",                 name: "Egg Noodles",                 price: 7.99,  category: "Fried Rice & Noodles", veg: false, emoji: "🍜", desc: "Noodles stir-fried with egg." },
  { id: "chicken-noodles",             name: "Chicken Noodles",             price: 7.99,  category: "Fried Rice & Noodles", veg: false, emoji: "🍜", desc: "Classic chicken stir-fried noodles." },
  { id: "prawn-noodles",               name: "Prawn Noodles",               price: 8.49,  category: "Fried Rice & Noodles", veg: false, emoji: "🍜", desc: "Noodles with prawns and spices." },

  // ── PIZZA (10" Medium prices) ────────────────────────────────────────────
  { id: "cheese-tomato-pizza",     name: "Cheese & Tomato Pizza",       price: 6.99,  category: "Pizza", veg: true,  emoji: "🍕", desc: "Tomatoes or BBQ sauce with cheese." },
  { id: "trawlers-pizza",          name: "Trawlers Pizza",              price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Pepperoni, spiced ground beef, turkey ham, mushroom, green peppers." },
  { id: "fungi-pizza",             name: "Fungi Pizza",                 price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Ham and sweetcorn on a classic base." },
  { id: "chicken-sweetcorn-pizza", name: "Chicken Sweetcorn Pizza",     price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Chicken and sweetcorn on a classic base." },
  { id: "pollo-pizza",             name: "Pollo Pizza",                 price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Chicken, mushroom, and herbs." },
  { id: "pepperoni-pizza",         name: "Pepperoni Pizza",             price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Classic pepperoni on a rich tomato base.", popular: true },
  { id: "veggie-supreme-pizza",    name: "Veggie Supreme Pizza",        price: 7.49,  category: "Pizza", veg: true,  emoji: "🍕", desc: "Green peppers, onion, tomatoes, sweetcorn, mushroom." },
  { id: "chicken-feast-pizza",     name: "Chicken Feast Pizza",         price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Chicken, sweetcorn, mushroom." },
  { id: "hawaiian-pizza",          name: "Hawaiian Pizza",              price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Turkey ham, mushroom, and pineapple." },
  { id: "indian-tandoor-pizza",    name: "Indian Tandoor Hot Pizza",    price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Green pepper, onion, tandoori chicken, mushroom, jalapeños." },
  { id: "hot-n-spicy-pizza",       name: "Hot N Spicy Pizza",           price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Beef, onion, green peppers, jalapeños." },
  { id: "american-hot-pizza",      name: "American Hot Pizza",          price: 7.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Pepperoni and jalapeños." },
  { id: "meat-feast-pizza",        name: "Meat Feast Pizza",            price: 8.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Pepperoni, spiced ground beef, turkey ham." },
  { id: "bbq-classic-pizza",       name: "BBQ Classic Pizza",           price: 8.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Pepperoni, spiced ground beef, pineapple, BBQ sauce." },
  { id: "tuna-delight-pizza",      name: "Tuna Delight Pizza",          price: 8.49,  category: "Pizza", veg: false, emoji: "🍕", desc: "Tuna and sweetcorn on a classic base." },

  // ── BURGERS & WRAPS ──────────────────────────────────────────────────────
  { id: "cheese-burger",           name: "Cheese Burger (¼lb)",         price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🍔", desc: "Classic cheese burger with fresh toppings." },
  { id: "chicken-burger",          name: "Chicken Burger (¼lb)",        price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🍔", desc: "Crispy chicken fillet burger." },
  { id: "chicken-ginger-burger",   name: "Chicken Ginger Burger",       price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🍔", desc: "Chicken burger with a ginger spiced kick." },
  { id: "peri-peri-chicken-burger",name: "Peri-Peri Chicken Burger",    price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🍔", desc: "Flame-grilled chicken with peri-peri sauce.", popular: true },
  { id: "chicken-donner-burger",   name: "Chicken Donner Burger",       price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🍔", desc: "Chicken donner meat in a classic bun." },
  { id: "meat-donner-burger",      name: "Meat Donner Burger",          price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🍔", desc: "Seasoned donner meat in a classic bun." },
  { id: "veg-burger",              name: "Veg Burger (¼lb)",            price: 3.99,  category: "Burgers & Wraps",     veg: true,  emoji: "🍔", desc: "Crispy vegetable patty with fresh toppings." },
  { id: "meat-donner-wrap",        name: "Meat Donner Wrap",            price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🌯", desc: "Seasoned donner meat wrapped in a soft flatbread." },
  { id: "chicken-donner-wrap",     name: "Chicken Donner Wrap",         price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🌯", desc: "Tender chicken donner wrapped with fresh salad." },
  { id: "chicken-stripper-wrap",   name: "Chicken Stripper Wrap",       price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🌯", desc: "Crispy chicken strips wrapped with salad and sauce." },
  { id: "peri-peri-wrap",          name: "Peri-Peri Wrap",              price: 3.99,  category: "Burgers & Wraps",     veg: false, emoji: "🌯", desc: "Peri-peri chicken wrapped with salad and sauce." },
  { id: "paneer-wrap",             name: "Paneer Wrap",                 price: 4.49,  category: "Burgers & Wraps",     veg: true,  emoji: "🌯", desc: "Grilled paneer wrapped with fresh salad and mint sauce." },

  // ── FISH & CHIPS ─────────────────────────────────────────────────────────
  { id: "fish-and-chips",          name: "Fish & Chips (Regular)",      price: 9.00,  category: "Fish & Chips",        veg: false, emoji: "🐟", desc: "Classic battered fish with chips. Choice of curry, gravy, beans, mushy peas, or no sauce.", popular: true },
  { id: "fish-and-chips-large",    name: "Fish & Chips (Large)",        price: 13.00, category: "Fish & Chips",        veg: false, emoji: "🐟", desc: "Large battered fish with a big portion of chips." },
  { id: "fish-regular",            name: "Fish (Regular)",              price: 8.00,  category: "Fish & Chips",        veg: false, emoji: "🐟", desc: "Golden battered fish fillet." },
  { id: "fish-cake",               name: "Fish Cake",                   price: 2.49,  category: "Fish & Chips",        veg: false, emoji: "🫓", desc: "Classic fish cake, crispy and golden." },
  { id: "chips-regular",           name: "Chips (Regular)",             price: 2.49,  category: "Fish & Chips",        veg: true,  emoji: "🍟", desc: "Crispy golden chips." },
  { id: "chips-cheese",            name: "Chips & Cheese",              price: 3.49,  category: "Fish & Chips",        veg: true,  emoji: "🍟", desc: "Chips topped with grated cheese." },

  // ── BEVERAGES ─────────────────────────────────────────────────────────────
  { id: "vanilla-thick-shake",     name: "Vanilla Thick Shake",         price: 3.99,  category: "Beverages",           veg: true,  emoji: "🥤", desc: "Rich and creamy vanilla-flavoured shake." },
  { id: "kitkat-thick-shake",      name: "Kit-Kat Thick Shake",         price: 4.49,  category: "Beverages",           veg: true,  emoji: "🥤", desc: "Chocolate shake blended with Kit-Kat pieces." },
  { id: "oreo-thick-shake",        name: "Oreo Thick Shake",            price: 4.49,  category: "Beverages",           veg: true,  emoji: "🥤", desc: "Creamy shake with crushed Oreo biscuits." },
  { id: "nutella-thick-shake",     name: "Nutella Thick Shake",         price: 4.49,  category: "Beverages",           veg: true,  emoji: "🥤", desc: "Chocolate hazelnut shake with Nutella." },
  { id: "brownie-thick-shake",     name: "Brownie Thick Shake",         price: 4.99,  category: "Beverages",           veg: true,  emoji: "🥤", desc: "Rich chocolate shake blended with brownie chunks." },
  { id: "vanilla-milkshake",       name: "Vanilla Milkshake",           price: 3.49,  category: "Beverages",           veg: true,  emoji: "🥛", desc: "Classic smooth vanilla shake." },
  { id: "banana-milkshake",        name: "Banana Milkshake",            price: 3.99,  category: "Beverages",           veg: true,  emoji: "🥛", desc: "Fresh banana blended into a creamy shake." },
  { id: "strawberry-milkshake",    name: "Strawberry Milkshake",        price: 3.99,  category: "Beverages",           veg: true,  emoji: "🥛", desc: "Sweet strawberry-flavoured shake." },
  { id: "blueberry-milkshake",     name: "Blueberry Milkshake",         price: 3.99,  category: "Beverages",           veg: true,  emoji: "🥛", desc: "Fruity blueberry milkshake." },
  { id: "salty-lassi",             name: "Salty Lassi",                 price: 1.99,  category: "Beverages",           veg: true,  emoji: "🥛", desc: "Refreshing yogurt drink with a pinch of salt." },
  { id: "sweet-lassi",             name: "Sweet Lassi",                 price: 2.49,  category: "Beverages",           veg: true,  emoji: "🥛", desc: "Traditional sweet yogurt drink." },
  { id: "mango-lassi",             name: "Mango Lassi",                 price: 2.99,  category: "Beverages",           veg: true,  emoji: "🥭", desc: "Creamy yogurt blended with mango pulp.", popular: true },
  { id: "coke-can",                name: "Coke Can (330ml)",            price: 1.30,  category: "Beverages",           veg: true,  emoji: "🥤", desc: "Ice-cold Coca-Cola can." },
  { id: "masala-tea",              name: "Masala Tea",                  price: 1.00,  category: "Beverages",           veg: true,  emoji: "🍵", desc: "Freshly brewed spiced Indian tea." },
  { id: "water-bottle",            name: "Water (500ml)",               price: 1.30,  category: "Beverages",           veg: true,  emoji: "💧", desc: "Still mineral water." },

  // ── DESSERTS ──────────────────────────────────────────────────────────────
  { id: "gulab-jamun",             name: "Gulab Jamun (4 pcs)",         price: 2.99,  category: "Desserts",            veg: true,  emoji: "🍮", desc: "Warm milk dumplings drenched in cardamom-rose syrup.", popular: true },
  { id: "gulab-jamun-ice-cream",   name: "Gulab Jamun with Ice Cream",  price: 3.99,  category: "Desserts",            veg: true,  emoji: "🍨", desc: "Classic gulab jamun served with a scoop of vanilla ice cream." },
  { id: "double-ka-meetha",        name: "Double Ka Meetha",            price: 3.49,  category: "Desserts",            veg: true,  emoji: "🍞", desc: "Hyderabadi bread pudding soaked in sugar syrup and cream." },
];

export const COUPONS: Coupon[] = [
  { id: "C1", code: "SHEFFIELD10", title: "10% off for Sheffield locals",  discount: 10, type: "percent", minOrder: 25, expiry: "Dec 2026", active: true, uses: 124, maxUses: 500 },
  { id: "C2", code: "BIRYANI20",   title: "20% off any Biryani dish",      discount: 20, type: "percent", minOrder: 15, expiry: "Aug 2026", active: true, uses: 87,  maxUses: 200 },
  { id: "C3", code: "WELCOME15",   title: "15% off your first order",      discount: 15, type: "percent", minOrder: 20, expiry: "Dec 2026", active: true, uses: 312, maxUses: undefined },
  { id: "C4", code: "SAVE5",       title: "£5 off orders over £30",        discount: 5,  type: "flat",    minOrder: 30, expiry: "Sep 2026", active: false, uses: 43, maxUses: 100 },
];

export const REVIEWS: Review[] = [
  { name: "Priya Krishnan", rating: 5, text: "The Chicken Dum Biryani is absolutely incredible — slow-cooked to perfection. Best South Indian food in Sheffield, hands down.", role: "Local regular" },
  { name: "James Holloway", rating: 5, text: "Fish & Chips here are proper northern style, and the masala dosa is a revelation. We come back every Friday.", role: "Verified diner" },
  { name: "Aarti Sharma",   rating: 5, text: "Chilli Paneer with a mango lassi — Sheffield's perfect Saturday night. Service is warm, food arrives fast.", role: "Loyalty member" },
];

export const TABS = [
  { id: "home",    label: "Home" },
  { id: "menu",    label: "Menu" },
  { id: "order",   label: "Order" },
  { id: "offers",  label: "Offers" },
  { id: "about",   label: "About" },
  { id: "contact", label: "Contact" },
] as const;
